run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
      #    - depguard
      #    - dupl
    - errcheck
      #    - goconst
      #    - gocritic
    - gocyclo
    - gofmt
      #    - goimports
    - goprintffuncname
      #    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
      #    - nakedret
      #    - prealloc
      #    - revive         # Replaces golint
    - staticcheck
      #    - stylecheck
    - typecheck
    - unconvert
      #    - unparam
      #    - unused         # Covers deadcode, structcheck, varcheck
      #    - whitespace
